/**
 * Справочник турниров: ключ файла openfootball → метаданные турнира.
 * Названия лиг — официальные, таймзоны — страна проведения.
 */
export const LEAGUES = {
  'en.1': { name: 'Premier League', ru: 'Английская Премьер-лига', country: 'England', countryRu: 'Англия', tz: 'Europe/London', tier: 1, accent: '#3d195b' },
  'en.2': { name: 'EFL Championship', ru: 'Чемпионшип', country: 'England', countryRu: 'Англия', tz: 'Europe/London', tier: 2, accent: '#2b2b2b' },
  'en.3': { name: 'EFL League One', ru: 'Первая лига Англии', country: 'England', countryRu: 'Англия', tz: 'Europe/London', tier: 3, accent: '#3f6fb5' },
  'en.4': { name: 'EFL League Two', ru: 'Вторая лига Англии', country: 'England', countryRu: 'Англия', tz: 'Europe/London', tier: 4, accent: '#4a7fbf' },
  'es.1': { name: 'LaLiga', ru: 'Ла Лига', country: 'Spain', countryRu: 'Испания', tz: 'Europe/Madrid', tier: 1, accent: '#ff4b44' },
  'es.2': { name: 'LaLiga Hypermotion', ru: 'Сегунда', country: 'Spain', countryRu: 'Испания', tz: 'Europe/Madrid', tier: 2, accent: '#c0392b' },
  'de.1': { name: 'Bundesliga', ru: 'Бундеслига', country: 'Germany', countryRu: 'Германия', tz: 'Europe/Berlin', tier: 1, accent: '#d20515' },
  'de.2': { name: '2. Bundesliga', ru: 'Вторая Бундеслига', country: 'Germany', countryRu: 'Германия', tz: 'Europe/Berlin', tier: 2, accent: '#a3040f' },
  'de.3': { name: '3. Liga', ru: 'Третья лига Германии', country: 'Germany', countryRu: 'Германия', tz: 'Europe/Berlin', tier: 3, accent: '#7d0a13' },
  'it.1': { name: 'Serie A', ru: 'Серия А', country: 'Italy', countryRu: 'Италия', tz: 'Europe/Rome', tier: 1, accent: '#008fd7' },
  'it.2': { name: 'Serie B', ru: 'Серия Б', country: 'Italy', countryRu: 'Италия', tz: 'Europe/Rome', tier: 2, accent: '#0f6ba8' },
  'fr.1': { name: 'Ligue 1', ru: 'Лига 1', country: 'France', countryRu: 'Франция', tz: 'Europe/Paris', tier: 1, accent: '#091c3e' },
  'fr.2': { name: 'Ligue 2', ru: 'Лига 2', country: 'France', countryRu: 'Франция', tz: 'Europe/Paris', tier: 2, accent: '#14315c' },
  'nl.1': { name: 'Eredivisie', ru: 'Эредивизи', country: 'Netherlands', countryRu: 'Нидерланды', tz: 'Europe/Amsterdam', tier: 1, accent: '#ff6600' },
  'pt.1': { name: 'Primeira Liga', ru: 'Примейра-лига', country: 'Portugal', countryRu: 'Португалия', tz: 'Europe/Lisbon', tier: 1, accent: '#006600' },
  'ru.1': { name: 'Russian Premier League', ru: 'Российская Премьер-лига', country: 'Russia', countryRu: 'Россия', tz: 'Europe/Moscow', tier: 1, accent: '#1a2f6b' },
  'ru.2': { name: 'Russian First League', ru: 'Первая лига России', country: 'Russia', countryRu: 'Россия', tz: 'Europe/Moscow', tier: 2, accent: '#27408b' },
  'at.1': { name: 'Bundesliga (Austria)', ru: 'Бундеслига Австрии', country: 'Austria', countryRu: 'Австрия', tz: 'Europe/Vienna', tier: 1, accent: '#c8102e' },
  'at.2': { name: '2. Liga (Austria)', ru: 'Вторая лига Австрии', country: 'Austria', countryRu: 'Австрия', tz: 'Europe/Vienna', tier: 2, accent: '#8c0b20' },
  'be.1': { name: 'Pro League', ru: 'Лига Жюпиле', country: 'Belgium', countryRu: 'Бельгия', tz: 'Europe/Brussels', tier: 1, accent: '#f5c518' },
  'ch.1': { name: 'Super League', ru: 'Суперлига Швейцарии', country: 'Switzerland', countryRu: 'Швейцария', tz: 'Europe/Zurich', tier: 1, accent: '#e30613' },
  'ch.2': { name: 'Challenge League', ru: 'Челлендж-лига', country: 'Switzerland', countryRu: 'Швейцария', tz: 'Europe/Zurich', tier: 2, accent: '#a80410' },
  'gr.1': { name: 'Super League Greece', ru: 'Суперлига Греции', country: 'Greece', countryRu: 'Греция', tz: 'Europe/Athens', tier: 1, accent: '#0d5eaf' },
  'tr.1': { name: 'Süper Lig', ru: 'Суперлига Турции', country: 'Türkiye', countryRu: 'Турция', tz: 'Europe/Istanbul', tier: 1, accent: '#e30a17' },
  'tr.2': { name: '1. Lig', ru: 'Первая лига Турции', country: 'Türkiye', countryRu: 'Турция', tz: 'Europe/Istanbul', tier: 2, accent: '#a80711' },
  'sco.1': { name: 'Scottish Premiership', ru: 'Шотландская Премьершип', country: 'Scotland', countryRu: 'Шотландия', tz: 'Europe/London', tier: 1, accent: '#1c3f94' },
  'cz.1': { name: 'Fortuna:Liga', ru: 'Первая лига Чехии', country: 'Czechia', countryRu: 'Чехия', tz: 'Europe/Prague', tier: 1, accent: '#11457e' },
  'hu.1': { name: 'NB I', ru: 'НБ I Венгрии', country: 'Hungary', countryRu: 'Венгрия', tz: 'Europe/Budapest', tier: 1, accent: '#cd2a3e' },
  'mx.1': { name: 'Liga MX', ru: 'Лига МХ', country: 'Mexico', countryRu: 'Мексика', tz: 'America/Mexico_City', tier: 1, accent: '#00a651' },
  'ar.1': { name: 'Liga Profesional', ru: 'Лига Профессиональ Аргентины', country: 'Argentina', countryRu: 'Аргентина', tz: 'America/Argentina/Buenos_Aires', tier: 1, accent: '#75aadb' },
  'br.1': { name: 'Brasileirão Série A', ru: 'Бразилейрао Серия А', country: 'Brazil', countryRu: 'Бразилия', tz: 'America/Sao_Paulo', tier: 1, accent: '#009739' },
  'br.2': { name: 'Brasileirão Série B', ru: 'Бразилейрао Серия Б', country: 'Brazil', countryRu: 'Бразилия', tz: 'America/Sao_Paulo', tier: 2, accent: '#007a2e' },
  'cn.1': { name: 'Chinese Super League', ru: 'Суперлига Китая', country: 'China', countryRu: 'Китай', tz: 'Asia/Shanghai', tier: 1, accent: '#c8102e' },
  'jp.1': { name: 'J1 League', ru: 'Джей-лига 1', country: 'Japan', countryRu: 'Япония', tz: 'Asia/Tokyo', tier: 1, accent: '#0b2d5c' },
  'co.1': { name: 'Categoría Primera A', ru: 'Примера А Колумбии', country: 'Colombia', countryRu: 'Колумбия', tz: 'America/Bogota', tier: 1, accent: '#fcd116' },
  'mls': { name: 'Major League Soccer', ru: 'МЛС', country: 'USA', countryRu: 'США', tz: 'America/New_York', tier: 1, accent: '#001f3f' },
  'copa.l': { name: 'Copa de la Liga', ru: 'Копа де ла Лига', country: 'Argentina', countryRu: 'Аргентина', tz: 'America/Argentina/Buenos_Aires', tier: 1, accent: '#6cace4', kind: 'cup' },
  'uefa.cl': { name: 'UEFA Champions League', ru: 'Лига чемпионов УЕФА', country: 'Europe', countryRu: 'Европа', tz: 'Europe/Berlin', tier: 1, accent: '#00204a', kind: 'international' },
  'at.cup': { name: 'ÖFB-Cup', ru: 'Кубок Австрии', country: 'Austria', countryRu: 'Австрия', tz: 'Europe/Vienna', tier: 1, accent: '#c8102e', kind: 'cup' },
  'de.cup': { name: 'DFB-Pokal', ru: 'Кубок Германии', country: 'Germany', countryRu: 'Германия', tz: 'Europe/Berlin', tier: 1, accent: '#d20515', kind: 'cup' },
  'dz.1': { name: 'Ligue 1 (Algeria)', ru: 'Лига 1 Алжира', country: 'Algeria', countryRu: 'Алжир', tz: 'Africa/Algiers', tier: 1, accent: '#006233' },
  'eg.1': { name: 'Egyptian Premier League', ru: 'Премьер-лига Египта', country: 'Egypt', countryRu: 'Египет', tz: 'Africa/Cairo', tier: 1, accent: '#c8102e' },
  'ma.1': { name: 'Botola Pro', ru: 'Ботола Про Марокко', country: 'Morocco', countryRu: 'Марокко', tz: 'Africa/Casablanca', tier: 1, accent: '#c1272d' },
  'au.1': { name: 'A-League Men', ru: 'А-Лига', country: 'Australia', countryRu: 'Австралия', tz: 'Australia/Sydney', tier: 1, accent: '#00843d' },
};

/** Турниры из текстовых файлов openfootball/europe/<страна>/<файл>. */
export const EURO_TEXT_LEAGUES = {
  ru1: { key: 'ru.1', name: 'Russian Premier League', ru: 'Российская Премьер-лига', country: 'Russia', countryRu: 'Россия', tz: 'Europe/Moscow', tier: 1, accent: '#1a2f6b' },
  ru2: { key: 'ru.2', name: 'Russian First League', ru: 'Первая лига России', country: 'Russia', countryRu: 'Россия', tz: 'Europe/Moscow', tier: 2, accent: '#27408b' },
  fr1: { key: 'fr.1', name: 'Ligue 1', ru: 'Лига 1', country: 'France', countryRu: 'Франция', tz: 'Europe/Paris', tier: 1, accent: '#091c3e' },
  nl1: { key: 'nl.1', name: 'Eredivisie', ru: 'Эредивизи', country: 'Netherlands', countryRu: 'Нидерланды', tz: 'Europe/Amsterdam', tier: 1, accent: '#ff6600' },
  pt1: { key: 'pt.1', name: 'Primeira Liga', ru: 'Примейра-лига', country: 'Portugal', countryRu: 'Португалия', tz: 'Europe/Lisbon', tier: 1, accent: '#006600' },
  sco1: { key: 'sco.1', name: 'Scottish Premiership', ru: 'Шотландская Премьершип', country: 'Scotland', countryRu: 'Шотландия', tz: 'Europe/London', tier: 1, accent: '#1c3f94' },
  tr1: { key: 'tr.1', name: 'Süper Lig', ru: 'Суперлига Турции', country: 'Türkiye', countryRu: 'Турция', tz: 'Europe/Istanbul', tier: 1, accent: '#e30a17' },
  no1: { key: 'no.1', name: 'Eliteserien', ru: 'Элитесериен', country: 'Norway', countryRu: 'Норвегия', tz: 'Europe/Oslo', tier: 1, accent: '#ba0c2f' },
  se1: { key: 'se.1', name: 'Allsvenskan', ru: 'Аллсвенскан', country: 'Sweden', countryRu: 'Швеция', tz: 'Europe/Stockholm', tier: 1, accent: '#006aa7' },
  dk1: { key: 'dk.1', name: 'Superligaen', ru: 'Суперлига Дании', country: 'Denmark', countryRu: 'Дания', tz: 'Europe/Copenhagen', tier: 1, accent: '#c60c30' },
  pl1: { key: 'pl.1', name: 'Ekstraklasa', ru: 'Экстракласса', country: 'Poland', countryRu: 'Польша', tz: 'Europe/Warsaw', tier: 1, accent: '#d22630' },
  ch1: { key: 'ch.1', name: 'Super League', ru: 'Суперлига Швейцарии', country: 'Switzerland', countryRu: 'Швейцария', tz: 'Europe/Zurich', tier: 1, accent: '#e30613' },
  be1: { key: 'be.1', name: 'Pro League', ru: 'Лига Жюпиле', country: 'Belgium', countryRu: 'Бельгия', tz: 'Europe/Brussels', tier: 1, accent: '#f5c518' },
  gr1: { key: 'gr.1', name: 'Super League Greece', ru: 'Суперлига Греции', country: 'Greece', countryRu: 'Греция', tz: 'Europe/Athens', tier: 1, accent: '#0d5eaf' },
  cz1: { key: 'cz.1', name: 'Fortuna:Liga', ru: 'Первая лига Чехии', country: 'Czechia', countryRu: 'Чехия', tz: 'Europe/Prague', tier: 1, accent: '#11457e' },
  at1: { key: 'at.1', name: 'Bundesliga (Austria)', ru: 'Бундеслига Австрии', country: 'Austria', countryRu: 'Австрия', tz: 'Europe/Vienna', tier: 1, accent: '#c8102e' },
  ua1: { key: 'ua.1', name: 'Ukrainian Premier League', ru: 'Премьер-лига Украины', country: 'Ukraine', countryRu: 'Украина', tz: 'Europe/Kyiv', tier: 1, accent: '#005bbb' },
  rs1: { key: 'rs.1', name: 'SuperLiga Srbije', ru: 'Суперлига Сербии', country: 'Serbia', countryRu: 'Сербия', tz: 'Europe/Belgrade', tier: 1, accent: '#c6363c' },
  hr1: { key: 'hr.1', name: 'HNL', ru: 'ХНЛ Хорватии', country: 'Croatia', countryRu: 'Хорватия', tz: 'Europe/Zagreb', tier: 1, accent: '#ff0000' },
  ro1: { key: 'ro.1', name: 'SuperLiga', ru: 'Суперлига Румынии', country: 'Romania', countryRu: 'Румыния', tz: 'Europe/Bucharest', tier: 1, accent: '#002b7f' },
  hu1: { key: 'hu.1', name: 'NB I', ru: 'НБ I Венгрии', country: 'Hungary', countryRu: 'Венгрия', tz: 'Europe/Budapest', tier: 1, accent: '#cd2a3e' },
  sk1: { key: 'sk.1', name: 'Niké Liga', ru: 'Нике Лига Словакии', country: 'Slovakia', countryRu: 'Словакия', tz: 'Europe/Bratislava', tier: 1, accent: '#0b4ea2' },
  si1: { key: 'si.1', name: 'PrvaLiga', ru: 'Первая лига Словении', country: 'Slovenia', countryRu: 'Словения', tz: 'Europe/Ljubljana', tier: 1, accent: '#005da4' },
  bg1: { key: 'bg.1', name: 'First League', ru: 'Первая лига Болгарии', country: 'Bulgaria', countryRu: 'Болгария', tz: 'Europe/Sofia', tier: 1, accent: '#00966e' },
  by1: { key: 'by.1', name: 'Vysshaya Liga', ru: 'Высшая лига Беларуси', country: 'Belarus', countryRu: 'Беларусь', tz: 'Europe/Minsk', tier: 1, accent: '#c8313e' },
  fi1: { key: 'fi.1', name: 'Veikkausliiga', ru: 'Вейккауслиига', country: 'Finland', countryRu: 'Финляндия', tz: 'Europe/Helsinki', tier: 1, accent: '#003580' },
  is1: { key: 'is.1', name: 'Besta deildin', ru: 'Беста-дейльдин', country: 'Iceland', countryRu: 'Исландия', tz: 'Atlantic/Reykjavik', tier: 1, accent: '#02529c' },
  ie1: { key: 'ie.1', name: 'League of Ireland Premier Division', ru: 'Премьер-дивизион Ирландии', country: 'Ireland', countryRu: 'Ирландия', tz: 'Europe/Dublin', tier: 1, accent: '#169b62' },
  nirl1: { key: 'nirl.1', name: 'NIFL Premiership', ru: 'Премьершип Сев. Ирландии', country: 'Northern Ireland', countryRu: 'Сев. Ирландия', tz: 'Europe/London', tier: 1, accent: '#00693e' },
  wls1: { key: 'wls.1', name: 'Cymru Premier', ru: 'Кимру Премьер', country: 'Wales', countryRu: 'Уэльс', tz: 'Europe/London', tier: 1, accent: '#c8102e' },
  ee1: { key: 'ee.1', name: 'Meistriliiga', ru: 'Мейстрилиига', country: 'Estonia', countryRu: 'Эстония', tz: 'Europe/Tallinn', tier: 1, accent: '#0072ce' },
  lv1: { key: 'lv.1', name: 'Virsliga', ru: 'Вирслига', country: 'Latvia', countryRu: 'Латвия', tz: 'Europe/Riga', tier: 1, accent: '#9e3039' },
  lt1: { key: 'lt.1', name: 'A Lyga', ru: 'А Лига Литвы', country: 'Lithuania', countryRu: 'Литва', tz: 'Europe/Vilnius', tier: 1, accent: '#fdb913' },
  md1: { key: 'md.1', name: 'Super Liga', ru: 'Суперлига Молдовы', country: 'Moldova', countryRu: 'Молдова', tz: 'Europe/Chisinau', tier: 1, accent: '#0046ae' },
  ge1: { key: 'ge.1', name: 'Erovnuli Liga', ru: 'Эровнули Лига', country: 'Georgia', countryRu: 'Грузия', tz: 'Asia/Tbilisi', tier: 1, accent: '#da291c' },
  am1: { key: 'am.1', name: 'Premier League (Armenia)', ru: 'Премьер-лига Армении', country: 'Armenia', countryRu: 'Армения', tz: 'Asia/Yerevan', tier: 1, accent: '#d90012' },
  az1: { key: 'az.1', name: 'Premyer Liqasi', ru: 'Премьер-лига Азербайджана', country: 'Azerbaijan', countryRu: 'Азербайджан', tz: 'Asia/Baku', tier: 1, accent: '#00b5e2' },
  kz1: { key: 'kz.1', name: 'Premier League (Kazakhstan)', ru: 'Премьер-лига Казахстана', country: 'Kazakhstan', countryRu: 'Казахстан', tz: 'Asia/Almaty', tier: 1, accent: '#00afca' },
  il1: { key: 'il.1', name: 'Ligat ha\'Al', ru: 'Лигат ха-Аль', country: 'Israel', countryRu: 'Израиль', tz: 'Asia/Jerusalem', tier: 1, accent: '#0038b8' },
  cy1: { key: 'cy.1', name: 'First Division (Cyprus)', ru: 'Первый дивизион Кипра', country: 'Cyprus', countryRu: 'Кипр', tz: 'Asia/Nicosia', tier: 1, accent: '#d57800' },
  mt1: { key: 'mt.1', name: 'BOV Premier League', ru: 'Премьер-лига Мальты', country: 'Malta', countryRu: 'Мальта', tz: 'Europe/Malta', tier: 1, accent: '#cf142b' },
  lu1: { key: 'lu.1', name: 'National Division', ru: 'Национальный дивизион Люксембурга', country: 'Luxembourg', countryRu: 'Люксембург', tz: 'Europe/Luxembourg', tier: 1, accent: '#00a1de' },
  li1: { key: 'li.1', name: '1. Liga (Liechtenstein)', ru: 'Первая лига Лихтенштейна', country: 'Liechtenstein', countryRu: 'Лихтенштейн', tz: 'Europe/Zurich', tier: 1, accent: '#002b7f' },
  sm1: { key: 'sm.1', name: 'Campionato Sammarinese', ru: 'Чемпионат Сан-Марино', country: 'San Marino', countryRu: 'Сан-Марино', tz: 'Europe/Rome', tier: 1, accent: '#73c2fb' },
  ad1: { key: 'ad.1', name: 'Primera Divisio', ru: 'Примера Дивизио Андорры', country: 'Andorra', countryRu: 'Андорра', tz: 'Europe/Andorra', tier: 1, accent: '#0032a0' },
  gi1: { key: 'gi.1', name: 'Football League (Gibraltar)', ru: 'Футбольная лига Гибралтара', country: 'Gibraltar', countryRu: 'Гибралтар', tz: 'Europe/Gibraltar', tier: 1, accent: '#c8102e' },
  mk1: { key: 'mk.1', name: 'First League (N. Macedonia)', ru: 'Первая лига Сев. Македонии', country: 'North Macedonia', countryRu: 'Сев. Македония', tz: 'Europe/Skopje', tier: 1, accent: '#d20000' },
  me1: { key: 'me.1', name: 'First League (Montenegro)', ru: 'Первая лига Черногории', country: 'Montenegro', countryRu: 'Черногория', tz: 'Europe/Podgorica', tier: 1, accent: '#c40308' },
  ba1: { key: 'ba.1', name: 'Premijer Liga BiH', ru: 'Премьер-лига БиГ', country: 'Bosnia and Herzegovina', countryRu: 'Босния и Герцеговина', tz: 'Europe/Sarajevo', tier: 1, accent: '#002f6c' },
  al1: { key: 'al.1', name: 'Kategoria Superiore', ru: 'Категория Суперьоре', country: 'Albania', countryRu: 'Албания', tz: 'Europe/Tirane', tier: 1, accent: '#e41e20' },
  xk1: { key: 'xk.1', name: 'Superleague of Kosovo', ru: 'Суперлига Косова', country: 'Kosovo', countryRu: 'Косово', tz: 'Europe/Belgrade', tier: 1, accent: '#244aa5' },
  fo1: { key: 'fo.1', name: 'Betri deildin', ru: 'Бетри-дейльдин', country: 'Faroe Islands', countryRu: 'Фарерские острова', tz: 'Atlantic/Faroe', tier: 1, accent: '#0065bd' },
};

/** Турниры StatsBomb (competition_id / season_id). */
/**
 * `ru`    — название конкретного розыгрыша («Евро-2024»), уходит в seasons.label_ru.
 * `ruComp`— название турнира без розыгрыша («Чемпионат Европы»), уходит в
 *           competitions.name_ru. Раньше в турнир писался `ru`, и из-за этого
 *           финал Евро-2024 Испания — Англия показывался как «Евро-2020».
 */
export const STATSBOMB_COMPETITIONS = {
  '43/106': { ruComp: 'Чемпионат мира', name: 'FIFA World Cup', ru: 'Чемпионат мира 2022', country: 'International', countryRu: 'Мир', kind: 'international', tz: 'Asia/Qatar', accent: '#8c1d40', withEvents: true },
  '55/282': { ruComp: 'Чемпионат Европы', name: 'UEFA Euro', ru: 'Евро-2024', country: 'International', countryRu: 'Европа', kind: 'international', tz: 'Europe/Berlin', accent: '#1a2f6b', withEvents: true },
  '55/43': { ruComp: 'Чемпионат Европы', name: 'UEFA Euro', ru: 'Евро-2020', country: 'International', countryRu: 'Европа', kind: 'international', tz: 'Europe/Berlin', accent: '#1a2f6b', withEvents: true },
  '223/282': { ruComp: 'Копа Америка', name: 'Copa América', ru: 'Копа Америка 2024', country: 'South America', countryRu: 'Южная Америка', kind: 'international', tz: 'America/New_York', accent: '#002868', withEvents: true },
  '16/4': { ruComp: 'Лига чемпионов', name: 'UEFA Champions League', ru: 'Лига чемпионов 2018/19', country: 'Europe', countryRu: 'Европа', kind: 'international', tz: 'Europe/Berlin', accent: '#00204a' },
  '11/90': { ruComp: 'Ла Лига', name: 'La Liga', ru: 'Ла Лига 2020/21', country: 'Spain', countryRu: 'Испания', tz: 'Europe/Madrid', accent: '#ff4b44' },
  '2/27': { ruComp: 'Английская Премьер-лига', name: 'Premier League', ru: 'АПЛ 2015/16', country: 'England', countryRu: 'Англия', tz: 'Europe/London', accent: '#3d195b' },
  '9/281': { ruComp: 'Бундеслига', name: '1. Bundesliga', ru: 'Бундеслига 2023/24', country: 'Germany', countryRu: 'Германия', tz: 'Europe/Berlin', accent: '#d20515' },
  '7/235': { ruComp: 'Лига 1', name: 'Ligue 1', ru: 'Лига 1 2022/23', country: 'France', countryRu: 'Франция', tz: 'Europe/Paris', accent: '#091c3e' },
};
