import { teamKey, slug } from '../lib/names.js';
import { getDb } from '../server/db.js';

/**
 * Русские названия клубов и сборных. Это перевод отображаемого имени,
 * сами команды приходят из внешних источников (openfootball / StatsBomb).
 */
export const TEAM_RU = {
  // Россия
  'zenit-st-petersburg': { ru: 'Зенит', short: 'ЗЕН' },
  'zenit': { ru: 'Зенит', short: 'ЗЕН' },
  'spartak-moskva': { ru: 'Спартак М', short: 'СПА' },
  'cska-moskva': { ru: 'ЦСКА', short: 'ЦСК' },
  'lokomotiv-moskva': { ru: 'Локомотив', short: 'ЛОК' },
  'dinamo-moskva': { ru: 'Динамо М', short: 'ДИН' },
  'fk-krasnodar': { ru: 'Краснодар', short: 'КРА' },
  'fk-rostov': { ru: 'Ростов', short: 'РОС' },
  'fk-orenburg': { ru: 'Оренбург', short: 'ОРЕН' },
  'akron-tolyatti': { ru: 'Акрон', short: 'АКР' },
  'krylia-sovetov': { ru: 'Крылья Советов', short: 'КС' },
  'akhmat-grozny': { ru: 'Ахмат', short: 'АХМ' },
  'rubin-kazan': { ru: 'Рубин', short: 'РУБ' },
  'fk-dinamo-makhachkala': { ru: 'Динамо Мх', short: 'ДМХ' },
  'fakel-voronezh': { ru: 'Факел', short: 'ФАК' },
  'fk-khimki': { ru: 'Химки', short: 'ХИМ' },
  'fk-nizhny-novgorod': { ru: 'Пари НН', short: 'ПНН' },
  'rodina': { ru: 'Родина', short: 'РОД' },
  'baltika-kaliningrad': { ru: 'Балтика', short: 'БАЛ' },
  'sochi': { ru: 'Сочи', short: 'СОЧ' },
  // Англия
  'arsenal': { ru: 'Арсенал', short: 'АРС' },
  'chelsea': { ru: 'Челси', short: 'ЧЕЛ' },
  'liverpool': { ru: 'Ливерпуль', short: 'ЛИВ' },
  'manchester-city': { ru: 'Манчестер Сити', short: 'МСИ' },
  'manchester-united': { ru: 'Манчестер Юнайтед', short: 'МЮ' },
  'tottenham-hotspur': { ru: 'Тоттенхэм', short: 'ТОТ' },
  'everton': { ru: 'Эвертон', short: 'ЭВЕ' },
  'newcastle-united': { ru: 'Ньюкасл', short: 'НЬЮ' },
  'bournemouth': { ru: 'Борнмут', short: 'БОР' },
  'aston-villa': { ru: 'Астон Вилла', short: 'АВЛ' },
  'west-ham-united': { ru: 'Вест Хэм', short: 'ВХЮ' },
  'brighton-hove-albion': { ru: 'Брайтон', short: 'БРА' },
  'crystal-palace': { ru: 'Кристал Пэлас', short: 'КП' },
  'brentford': { ru: 'Брентфорд', short: 'БРФ' },
  'fulham': { ru: 'Фулхэм', short: 'ФУЛ' },
  'wolverhampton-wanderers': { ru: 'Вулверхэмптон', short: 'ВУЛ' },
  'nottingham-forest': { ru: 'Ноттингем Форест', short: 'НФ' },
  'leeds-united': { ru: 'Лидс', short: 'ЛИД' },
  'leicester-city': { ru: 'Лестер', short: 'ЛЕС' },
  'sunderland': { ru: 'Сандерленд', short: 'САН' },
  'ipswich-town': { ru: 'Ипсвич', short: 'ИПС' },
  'burnley': { ru: 'Бернли', short: 'БРН' },
  'coventry-city': { ru: 'Ковентри', short: 'КОВ' },
  'hull-city': { ru: 'Халл Сити', short: 'ХАЛЛ' },
  'birmingham-city': { ru: 'Бирмингем', short: 'БИР' },
  'southampton': { ru: 'Саутгемптон', short: 'САУ' },
  // Испания
  'barcelona': { ru: 'Барселона', short: 'БАР' },
  'real-madrid': { ru: 'Реал Мадрид', short: 'РЕА' },
  'atletico-madrid': { ru: 'Атлетико', short: 'АТЛ' },
  'athletic-bilbao': { ru: 'Атлетик Бильбао', short: 'АТБ' },
  'real-sociedad': { ru: 'Реал Сосьедад', short: 'РСО' },
  'real-betis': { ru: 'Реал Бетис', short: 'БЕТ' },
  'villarreal': { ru: 'Вильярреал', short: 'ВИЛ' },
  'sevilla': { ru: 'Севилья', short: 'СЕВ' },
  'valencia': { ru: 'Валенсия', short: 'ВАЛ' },
  'girona': { ru: 'Жирона', short: 'ЖИР' },
  'celta-vigo': { ru: 'Сельта', short: 'СЕЛ' },
  'espanyol': { ru: 'Эспаньол', short: 'ЭСП' },
  'osasuna': { ru: 'Осасуна', short: 'ОСА' },
  'getafe': { ru: 'Хетафе', short: 'ХЕТ' },
  'mallorca': { ru: 'Мальорка', short: 'МАЛ' },
  'rayo-vallecano': { ru: 'Райо Вальекано', short: 'РАЙ' },
  'alaves': { ru: 'Алавес', short: 'АЛА' },
  'leganes': { ru: 'Леганес', short: 'ЛЕГ' },
  'valladolid': { ru: 'Вальядолид', short: 'ВЛЬ' },
  'las-palmas': { ru: 'Лас-Пальмас', short: 'ЛП' },
  'levante': { ru: 'Леванте', short: 'ЛЕВ' },
  'elche': { ru: 'Эльче', short: 'ЭЛЬ' },
  // Германия
  'bayern-munchen': { ru: 'Бавария', short: 'БАВ' },
  'bayern-munich': { ru: 'Бавария', short: 'БАВ' },
  'borussia-dortmund': { ru: 'Боруссия Д', short: 'БВБ' },
  'bayer-04-leverkusen': { ru: 'Байер', short: 'БАЙ' },
  'rb-leipzig': { ru: 'РБ Лейпциг', short: 'РБЛ' },
  'eintracht-frankfurt': { ru: 'Айнтрахт', short: 'АЙН' },
  'vfb-stuttgart': { ru: 'Штутгарт', short: 'ШТУ' },
  'vfl-wolfsburg': { ru: 'Вольфсбург', short: 'ВОЛ' },
  'borussia-monchengladbach': { ru: 'Боруссия М', short: 'БМГ' },
  'sc-freiburg': { ru: 'Фрайбург', short: 'ФРА' },
  'tsg-1899-hoffenheim': { ru: 'Хоффенхайм', short: 'ХОФ' },
  '1-fsv-mainz-05': { ru: 'Майнц', short: 'МАЙ' },
  'fc-union-berlin': { ru: 'Унион Берлин', short: 'УНИ' },
  'fc-augsburg': { ru: 'Аугсбург', short: 'АУГ' },
  'werder-bremen': { ru: 'Вердер', short: 'ВЕР' },
  'fc-sankt-pauli': { ru: 'Санкт-Паули', short: 'СПА' },
  'fc-heidenheim-1846': { ru: 'Хайденхайм', short: 'ХАЙ' },
  'holstein-kiel': { ru: 'Хольштайн Киль', short: 'ХОЛ' },
  'vfl-bochum': { ru: 'Бохум', short: 'БОХ' },
  // Италия
  'juventus': { ru: 'Ювентус', short: 'ЮВЕ' },
  'inter': { ru: 'Интер', short: 'ИНТ' },
  'milan': { ru: 'Милан', short: 'МИЛ' },
  'napoli': { ru: 'Наполи', short: 'НАП' },
  'roma': { ru: 'Рома', short: 'РОМ' },
  'lazio': { ru: 'Лацио', short: 'ЛАЦ' },
  'atalanta': { ru: 'Аталанта', short: 'АТА' },
  'fiorentina': { ru: 'Фиорентина', short: 'ФИО' },
  'bologna': { ru: 'Болонья', short: 'БОЛ' },
  'torino': { ru: 'Торино', short: 'ТОР' },
  'udinese': { ru: 'Удинезе', short: 'УДИ' },
  'genoa': { ru: 'Дженоа', short: 'ДЖЕ' },
  'cagliari': { ru: 'Кальяри', short: 'КАЛ' },
  'hellas-verona': { ru: 'Верона', short: 'ВЕР' },
  'lecce': { ru: 'Лечче', short: 'ЛЕЧ' },
  'empoli': { ru: 'Эмполи', short: 'ЭМП' },
  'monza': { ru: 'Монца', short: 'МОН' },
  'como': { ru: 'Комо', short: 'КОМ' },
  'parma': { ru: 'Парма', short: 'ПАР' },
  'venezia': { ru: 'Венеция', short: 'ВЕН' },
  'pisa': { ru: 'Пиза', short: 'ПИЗ' },
  'sassuolo': { ru: 'Сассуоло', short: 'САС' },
  'cremonese': { ru: 'Кремонезе', short: 'КРЕ' },
  // Франция
  'paris-saint-germain': { ru: 'ПСЖ', short: 'ПСЖ' },
  'olympique-marseille': { ru: 'Марсель', short: 'ОМ' },
  'olympique-lyonnais': { ru: 'Лион', short: 'ЛИОН' },
  'monaco': { ru: 'Монако', short: 'МОН' },
  'lille': { ru: 'Лилль', short: 'ЛИЛ' },
  'nice': { ru: 'Ницца', short: 'НИЦ' },
  'stade-rennais': { ru: 'Ренн', short: 'РЕН' },
  'rc-lens': { ru: 'Ланс', short: 'ЛАН' },
  'stade-brestois-29': { ru: 'Брест', short: 'БРЕ' },
  'stade-reims': { ru: 'Реймс', short: 'РЕЙ' },
  'nantes': { ru: 'Нант', short: 'НАН' },
  'toulouse': { ru: 'Тулуза', short: 'ТУЛ' },
  'strasbourg': { ru: 'Страсбур', short: 'СТР' },
  'auxerre': { ru: 'Осер', short: 'ОСЕ' },
  'le-havre': { ru: 'Гавр', short: 'ГАВ' },
  'angers': { ru: 'Анже', short: 'АНЖ' },
  'saint-etienne': { ru: 'Сент-Этьен', short: 'СЭТ' },
  'paris-fc': { ru: 'Париж', short: 'ПФК' },
  'metz': { ru: 'Мец', short: 'МЕЦ' },
  'lorient': { ru: 'Лорьян', short: 'ЛОР' },
  // Нидерланды / Португалия / прочее
  'ajax': { ru: 'Аякс', short: 'АЯК' },
  'psv': { ru: 'ПСВ', short: 'ПСВ' },
  'feyenoord': { ru: 'Фейеноорд', short: 'ФЕЙ' },
  'benfica': { ru: 'Бенфика', short: 'БЕН' },
  'porto': { ru: 'Порту', short: 'ПОР' },
  'sporting-cp': { ru: 'Спортинг', short: 'СПО' },
  'braga': { ru: 'Брага', short: 'БРГ' },
  'celtic': { ru: 'Селтик', short: 'СЕЛТ' },
  'rangers': { ru: 'Рейнджерс', short: 'РЕЙН' },
  'galatasaray': { ru: 'Галатасарай', short: 'ГАЛ' },
  'fenerbahce': { ru: 'Фенербахче', short: 'ФЕН' },
  'besiktas': { ru: 'Бешикташ', short: 'БЕШ' },
  'olympiacos': { ru: 'Олимпиакос', short: 'ОЛИ' },
  'red-bull-salzburg': { ru: 'Ред Булл Зальцбург', short: 'РБЗ' },
  // Сборные
  'france': { ru: 'Франция', short: 'FRA' },
  'spain': { ru: 'Испания', short: 'ESP' },
  'germany': { ru: 'Германия', short: 'GER' },
  'england': { ru: 'Англия', short: 'ENG' },
  'portugal': { ru: 'Португалия', short: 'POR' },
  'netherlands': { ru: 'Нидерланды', short: 'NED' },
  'italy': { ru: 'Италия', short: 'ITA' },
  'belgium': { ru: 'Бельгия', short: 'BEL' },
  'croatia': { ru: 'Хорватия', short: 'CRO' },
  'brazil': { ru: 'Бразилия', short: 'BRA' },
  'argentina': { ru: 'Аргентина', short: 'ARG' },
  'morocco': { ru: 'Марокко', short: 'MAR' },
  'japan': { ru: 'Япония', short: 'JPN' },
  'south-korea': { ru: 'Южная Корея', short: 'KOR' },
  'senegal': { ru: 'Сенегал', short: 'SEN' },
  'uruguay': { ru: 'Уругвай', short: 'URU' },
  'mexico': { ru: 'Мексика', short: 'MEX' },
  'usa': { ru: 'США', short: 'USA' },
  'united-states': { ru: 'США', short: 'USA' },
  'poland': { ru: 'Польша', short: 'POL' },
  'denmark': { ru: 'Дания', short: 'DEN' },
  'switzerland': { ru: 'Швейцария', short: 'SUI' },
  'serbia': { ru: 'Сербия', short: 'SRB' },
  'wales': { ru: 'Уэльс', short: 'WAL' },
  'scotland': { ru: 'Шотландия', short: 'SCO' },
  'turkey': { ru: 'Турция', short: 'TUR' },
  'austria': { ru: 'Австрия', short: 'AUT' },
  'ukraine': { ru: 'Украина', short: 'UKR' },
  'sweden': { ru: 'Швеция', short: 'SWE' },
  'norway': { ru: 'Норвегия', short: 'NOR' },
  'czech-republic': { ru: 'Чехия', short: 'CZE' },
  'greece': { ru: 'Греция', short: 'GRE' },
  'hungary': { ru: 'Венгрия', short: 'HUN' },
  'russia': { ru: 'Россия', short: 'RUS' },
  'colombia': { ru: 'Колумбия', short: 'COL' },
  'ecuador': { ru: 'Эквадор', short: 'ECU' },
  'chile': { ru: 'Чили', short: 'CHI' },
  'peru': { ru: 'Перу', short: 'PER' },
  'egypt': { ru: 'Египет', short: 'EGY' },
  'nigeria': { ru: 'Нигерия', short: 'NGA' },
  'cameroon': { ru: 'Камерун', short: 'CMR' },
  'ghana': { ru: 'Гана', short: 'GHA' },
  'algeria': { ru: 'Алжир', short: 'ALG' },
  'ivory-coast': { ru: 'Кот-д’Ивуар', short: 'CIV' },
  'south-africa': { ru: 'ЮАР', short: 'RSA' },
  'australia': { ru: 'Австралия', short: 'AUS' },
  'saudi-arabia': { ru: 'Саудовская Аравия', short: 'KSA' },
  'iran': { ru: 'Иран', short: 'IRN' },
  'qatar': { ru: 'Катар', short: 'QAT' },
  'canada': { ru: 'Канада', short: 'CAN' },
  'costa-rica': { ru: 'Коста-Рика', short: 'CRC' },
  'paraguay': { ru: 'Парагвай', short: 'PAR' },
  'bolivia': { ru: 'Боливия', short: 'BOL' },
  'venezuela': { ru: 'Венесуэла', short: 'VEN' },
  'panama': { ru: 'Панама', short: 'PAN' },
  'jamaica': { ru: 'Ямайка', short: 'JAM' },
  'tunisia': { ru: 'Тунис', short: 'TUN' },
  'mali': { ru: 'Мали', short: 'MLI' },
  'dr-congo': { ru: 'ДР Конго', short: 'COD' },
  'guinea': { ru: 'Гвинея', short: 'GUI' },
  'zambia': { ru: 'Замбия', short: 'ZAM' },
  'angola': { ru: 'Ангола', short: 'ANG' },
  'burkina-faso': { ru: 'Буркина-Фасо', short: 'BFA' },
  'cape-verde': { ru: 'Кабо-Верде', short: 'CPV' },
  'mauritania': { ru: 'Мавритания', short: 'MTN' },
  'gambia': { ru: 'Гамбия', short: 'GAM' },
  'comoros': { ru: 'Коморы', short: 'COM' },
  'equatorial-guinea': { ru: 'Экв. Гвинея', short: 'EQG' },
  'namibia': { ru: 'Намибия', short: 'NAM' },
  'mozambique': { ru: 'Мозамбик', short: 'MOZ' },
  'tanzania': { ru: 'Танзания', short: 'TAN' },
  'albania': { ru: 'Албания', short: 'ALB' },
  'romania': { ru: 'Румыния', short: 'ROU' },
  'slovakia': { ru: 'Словакия', short: 'SVK' },
  'slovenia': { ru: 'Словения', short: 'SVN' },
  'georgia': { ru: 'Грузия', short: 'GEO' },
  'finland': { ru: 'Финляндия', short: 'FIN' },
  'israel': { ru: 'Израиль', short: 'ISR' },
  'kosovo': { ru: 'Косово', short: 'KOS' },
  'cyprus': { ru: 'Кипр', short: 'CYP' },
  'belarus': { ru: 'Беларусь', short: 'BLR' },
  'bulgaria': { ru: 'Болгария', short: 'BUL' },
  'ireland': { ru: 'Ирландия', short: 'IRL' },
  'northern-ireland': { ru: 'Сев. Ирландия', short: 'NIR' },
  'estonia': { ru: 'Эстония', short: 'EST' },
  'latvia': { ru: 'Латвия', short: 'LVA' },
  'lithuania': { ru: 'Литва', short: 'LTU' },
  'luxembourg': { ru: 'Люксембург', short: 'LUX' },
  'north-macedonia': { ru: 'Сев. Македония', short: 'MKD' },
  'montenegro': { ru: 'Черногория', short: 'MNE' },
  'bosnia-herzegovina': { ru: 'Босния и Герцеговина', short: 'BIH' },
  'armenia': { ru: 'Армения', short: 'ARM' },
  'azerbaijan': { ru: 'Азербайджан', short: 'AZE' },
  'kazakhstan': { ru: 'Казахстан', short: 'KAZ' },
  'moldova': { ru: 'Молдова', short: 'MDA' },
  'faroe-islands': { ru: 'Фарерские о-ва', short: 'FRO' },
  'andorra': { ru: 'Андорра', short: 'AND' },
  'san-marino': { ru: 'Сан-Марино', short: 'SMR' },
  'gibraltar': { ru: 'Гибралтар', short: 'GIB' },
  'liechtenstein': { ru: 'Лихтенштейн', short: 'LIE' },
  'malta': { ru: 'Мальта', short: 'MLT' },
  'iceland': { ru: 'Исландия', short: 'ISL' },
  'new-zealand': { ru: 'Новая Зеландия', short: 'NZL' },
  'honduras': { ru: 'Гондурас', short: 'HON' },
  'el-salvador': { ru: 'Сальвадор', short: 'SLV' },
  'trinidad-tobago': { ru: 'Тринидад и Тобаго', short: 'TRI' },
  'haiti': { ru: 'Гаити', short: 'HAI' },
  'curacao': { ru: 'Кюрасао', short: 'CUW' },
  'uzbekistan': { ru: 'Узбекистан', short: 'UZB' },
  'jordan': { ru: 'Иордания', short: 'JOR' },
  'palestine': { ru: 'Палестина', short: 'PLE' },
  'iraq': { ru: 'Ирак', short: 'IRQ' },
  'china': { ru: 'Китай', short: 'CHN' },
  'india': { ru: 'Индия', short: 'IND' },
  'indonesia': { ru: 'Индонезия', short: 'IDN' },
  'thailand': { ru: 'Таиланд', short: 'THA' },
  'vietnam': { ru: 'Вьетнам', short: 'VIE' },
  'kenya': { ru: 'Кения', short: 'KEN' },
  'uganda': { ru: 'Уганда', short: 'UGA' },
  'sudan': { ru: 'Судан', short: 'SDN' },
  'libya': { ru: 'Ливия', short: 'LBY' },
  'zimbabwe': { ru: 'Зимбабве', short: 'ZIM' },
  'benin': { ru: 'Бенин', short: 'BEN' },
  'togo': { ru: 'Того', short: 'TOG' },
  'sierra-leone': { ru: 'Сьерра-Леоне', short: 'SLE' },
  'madagascar': { ru: 'Мадагаскар', short: 'MAD' },
  'botswana': { ru: 'Ботсвана', short: 'BOT' },
  'eswatini': { ru: 'Эсватини', short: 'SWZ' },
  'cuba': { ru: 'Куба', short: 'CUB' },
  'suriname': { ru: 'Суринам', short: 'SUR' },
  'guyana': { ru: 'Гайана', short: 'GUY' },
  'nicaragua': { ru: 'Никарагуа', short: 'NCA' },
  'guatemala': { ru: 'Гватемала', short: 'GUA' },
  'belize': { ru: 'Белиз', short: 'BLZ' },
};

/** Дополнительные известные варианты написания → ключ команды. */
export const TEAM_ALIASES = {
  'man-utd': 'manchester-united',
  'man-united': 'manchester-united',
  'man-city': 'manchester-city',
  'psg': 'paris-saint-germain',
  'atletico': 'atletico-madrid',
  'ath-bilbao': 'athletic-bilbao',
  'bayern': 'bayern-munchen',
  'dortmund': 'borussia-dortmund',
  'gladbach': 'borussia-monchengladbach',
  'leverkusen': 'bayer-04-leverkusen',
  'frankfurt': 'eintracht-frankfurt',
  'stuttgart': 'vfb-stuttgart',
  'inter-milan': 'inter',
  'ac-milan': 'milan',
  'verona': 'hellas-verona',
  'marseille': 'olympique-marseille',
  'lyon': 'olympique-lyonnais',
  'sociedad': 'real-sociedad',
  'betis': 'real-betis',
  'wolves': 'wolverhampton-wanderers',
  'west-ham': 'west-ham-united',
  'spurs': 'tottenham-hotspur',
  'nottm-forest': 'nottingham-forest',
  'brighton': 'brighton-hove-albion',
  'zenit': 'zenit-st-petersburg',
  'cska': 'cska-moskva',
  'lokomotiv': 'lokomotiv-moskva',
  'dinamo': 'dinamo-moskva',
  'krasnodar': 'fk-krasnodar',
  'rostov': 'fk-rostov',
  'orenburg': 'fk-orenburg',
  'khimki': 'fk-khimki',
  'rubin': 'rubin-kazan',
  // Названия из ESPN Site API → те же клубы
  'gazovik-orenburg': 'fk-orenburg',
  'lokomotiv-moscow': 'lokomotiv-moskva',
  'cska-moscow': 'cska-moskva',
  'spartak-moscow': 'spartak-moskva',
  'dinamo-moscow': 'dinamo-moskva',
  'fc-rostov': 'fk-rostov',
  'fc-krasnodar': 'fk-krasnodar',
  'fc-sochi': 'sochi',
  'fc-nizhny-novgorod': 'fk-nizhny-novgorod',
  'fc-baltika-kaliningrad': 'baltika-kaliningrad',
  'baltika': 'baltika-kaliningrad',
  'fc-akhmat-grozny': 'akhmat-grozny',
  'fc-rubin-kazan': 'rubin-kazan',
  'fc-pari-nn': 'fk-nizhny-novgorod',
  'fk-rodina': 'rodina',
};

export function resolveTeamKey(name) {
  const key = teamKey(name);
  return TEAM_ALIASES[key] || key;
}

export function displayName(name) {
  const key = resolveTeamKey(name);
  return TEAM_RU[key]?.ru || name;
}

export function shortName(name) {
  const key = resolveTeamKey(name);
  if (TEAM_RU[key]?.short) return TEAM_RU[key].short;
  const base = displayName(name).split(' ')[0];
  return base.slice(0, 3).toUpperCase();
}

/** Клубы с фирменным акцентным цветом (используется в карточках). */
export const TEAM_COLORS = {
  'zenit-st-petersburg': '#1899d6',
  'spartak-moskva': '#e4002b',
  'cska-moskva': '#d52b1e',
  'lokomotiv-moskva': '#e4002b',
  'dinamo-moskva': '#0055a4',
  'fk-krasnodar': '#1f8a4c',
  'fk-rostov': '#f7d618',
  'fk-orenburg': '#0057a3',
  'akron-tolyatti': '#0f9bd7',
  'krylia-sovetov': '#1c6db5',
  'akhmat-grozny': '#00a651',
  'rubin-kazan': '#c8102e',
  'arsenal': '#ef0107',
  'chelsea': '#034694',
  'liverpool': '#c8102e',
  'manchester-city': '#6cabdd',
  'manchester-united': '#da291c',
  'tottenham-hotspur': '#132257',
  'everton': '#003399',
  'newcastle-united': '#241f20',
  'bournemouth': '#da291c',
  'aston-villa': '#670e36',
  'west-ham-united': '#7a263a',
  'brighton-hove-albion': '#0057b8',
  'crystal-palace': '#1b458f',
  'brentford': '#e30613',
  'fulham': '#000000',
  'wolverhampton-wanderers': '#fdb913',
  'nottingham-forest': '#dd0000',
  'leeds-united': '#ffcd00',
  'barcelona': '#a50044',
  'real-madrid': '#febe10',
  'atletico-madrid': '#cb3524',
  'athletic-bilbao': '#ee2523',
  'real-sociedad': '#143c8c',
  'real-betis': '#00954c',
  'villarreal': '#ffe667',
  'sevilla': '#d8112d',
  'bayern-munchen': '#dc052d',
  'borussia-dortmund': '#fde100',
  'bayer-04-leverkusen': '#e32221',
  'rb-leipzig': '#dd0741',
  'eintracht-frankfurt': '#e1000f',
  'vfb-stuttgart': '#e32219',
  'juventus': '#000000',
  'inter': '#0068a8',
  'milan': '#fb090b',
  'napoli': '#12a0d7',
  'roma': '#8e1f2f',
  'lazio': '#87d8f7',
  'atalanta': '#1d71b8',
  'fiorentina': '#592781',
  'paris-saint-germain': '#004170',
  'olympique-marseille': '#2faee0',
  'olympique-lyonnais': '#1f4fa3',
  'monaco': '#ce1126',
  'lille': '#e01e13',
  'ajax': '#d2122e',
  'psv': '#ed1c24',
  'feyenoord': '#c8102e',
  'benfica': '#e30613',
  'porto': '#00428c',
  'sporting-cp': '#008057',
};

const upsertTeam = (name, extra = {}) => {
  const db = getDb();
  const key = resolveTeamKey(name);
  const meta = TEAM_RU[key] || {};
  const now = new Date().toISOString();
  db.prepare(
    `INSERT INTO teams (id, name, name_ru, short_name, country, crest_url, primary_color, statsbomb_id, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(id) DO UPDATE SET
       -- официальное название обычно длиннее («Arsenal FC» > «FK Arsenal»)
       name = CASE WHEN teams.name IS NULL OR length(excluded.name) > length(teams.name)
                   THEN excluded.name ELSE teams.name END,
       name_ru = COALESCE(excluded.name_ru, teams.name_ru),
       short_name = COALESCE(excluded.short_name, teams.short_name),
       country = COALESCE(excluded.country, teams.country),
       statsbomb_id = COALESCE(excluded.statsbomb_id, teams.statsbomb_id),
       primary_color = COALESCE(excluded.primary_color, teams.primary_color),
       updated_at = excluded.updated_at`,
  ).run(
    key,
    extra.name || name,
    meta.ru || extra.nameRu || null,
    meta.short || extra.short || null,
    extra.country || null,
    extra.crest || null,
    TEAM_COLORS[key] || extra.color || null,
    extra.statsbombId ?? null,
    now,
  );
  const alias = slug(name);
  if (alias) {
    db.prepare(
      `INSERT INTO team_aliases(alias, team_id) VALUES (?, ?)
       ON CONFLICT(alias) DO NOTHING`,
    ).run(alias, key);
  }
  return key;
};

export { upsertTeam };
